sel_chat = "Deepseek"
height = 600.0
width = 800.0
font_size = 18
rec_device = "Monitor of AudioQuest DragonFly Black v1.5 Analogowe stereo"
theme = "Catppuccin Mocha"
tr_model = "./ggml-large-v3-turbo-q5_0.bin"
tr_lang = "EN"
prompt_context = ""

[ai_chats.elevenlabs]
name = "Elevenlabs"
key = ""
url = "Model = voice, look voices list in app.toml for names"
model = "Lily"

[ai_chats.ollama_qwq]
name = "Ollama [qwq:32b]"
key = ""
url = "http://localhost:11434/v1"
model = "qwq:latest"

[ai_chats.gpt]
name = "Chat GPT"
key = ""
url = "https://api.openai.com/v1"
model = "gpt-4"

[ai_chats.ollama_deepseek]
name = "Ollama [deepseek-r1:32b]"
key = ""
url = "http://localhost:11434/v1"
model = "deepseek-r1:32b"

[ai_chats.deepseek]
name = "Deepseek"
key = ""
url = "https://api.deepseek.com"
model = "deepseek-chat"

[ai_chats.ollama_gemma]
name = "Ollama [gemma3:27b]"
key = ""
url = "http://localhost:11434/v1"
model = "gemma3:27b"

[voices]
Alice = "Xb7hH8MSUJpSbSDYk0k2"
Aria = "9BWtsMINqrJLrRacOk9x"
Bill = "pqHfZKP75CvOlQylNhV4"
Brian = "nPczCjzI2devNBz1zQrb"
Callum = "N2lVS1w4EtoT3dr4eOWO"
Charlie = "IKne3meq5aSn9XLyUdCD"
Charlotte = "XB0fDUnXU5powFXDhCwa"
Chris = "iP95p4xoKVk53GoZ742B"
Daniel = "onwK4e9ZLuTAKqWW03F9"
Eric = "cjVigY5qzO86Huf0OWal"
George = "JBFqnCBsd6RMkjVDRZzb"
Jessica = "cgSgspJ2msm6clMCkdW9"
Laura = "FGY2WhTYpPnrIDTdsKH5"
Liam = "TX3LPaxmHKxFdv7VOQHJ"
Lily = "pFZP5JQG7iQjIQuC4Bku"
Matilda = "XrExE9yKIg1WjnnlVkGX"
River = "SAz9YHcvj6GT2YYXdXww"
Roger = "CwhRBWXzGAHq8TQ4Fs17"
Sarah = "EXAVITQu4vr4xnSDxMaL"
Will = "bIHbv24MWmeRgasZH58o"
